const apiEndpoints = {
  athlete: {
    id: 28404658,
    username: 'quesada_dani',
    resource_state: 2,
    firstname: 'Dani',
    lastname: 'Quesada',
    city: null,
    state: null,
    country: null,
    sex: 'F',
    premium: false,
    summit: false,
    created_at: '2018-02-19T16:51:00Z',
    updated_at: '2020-09-01T10:30:19Z',
    badge_type_id: 0,
    profile_medium:
      'https://dgalywyr863hv.cloudfront.net/pictures/athletes/28404658/12542123/3/medium.jpg',
    profile:
      'https://dgalywyr863hv.cloudfront.net/pictures/athletes/28404658/12542123/3/large.jpg',
    friend: null,
    follower: null
  },
  activities: [
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 3451,
      elapsed_time: 3451,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4162060311,
      external_id:
        '2020-10-07_07-22-19_83ab63db-3e6c-42f7-b98a-fe8e55726f8b.tcx',
      upload_id: 4453137710,
      start_date: '2020-10-07T06:23:37Z',
      start_date_local: '2020-10-07T08:23:37Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 2,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4162060311',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4453137710',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 112.8,
      max_heartrate: 152.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'El reloj decidió no medir distancia ',
      distance: 0.0,
      moving_time: 3172,
      elapsed_time: 3172,
      total_elevation_gain: 0,
      type: 'Swim',
      id: 4160297652,
      external_id:
        '2020-10-06_19-56-31_2ed47e76-939b-4895-8568-6eee3998a75f.tcx',
      upload_id: 4451274179,
      start_date: '2020-10-06T19:02:36Z',
      start_date_local: '2020-10-06T21:02:36Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 4,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4160297652',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4451274179',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 129.1,
      max_heartrate: 163.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Carrera por la tarde',
      distance: 7019.0,
      moving_time: 2019,
      elapsed_time: 2357,
      total_elevation_gain: 13.1,
      type: 'Run',
      workout_type: null,
      id: 4149861944,
      external_id:
        '2020-10-04_12-30-12_98d54ba3-7c29-424c-af10-63beffc1de93.tcx',
      upload_id: 4440223872,
      start_date: '2020-10-04T11:49:24Z',
      start_date_local: '2020-10-04T13:49:24Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.39635, -3.696052],
      end_latlng: [40.395225, -3.705922],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.39635,
      start_longitude: -3.696052,
      achievement_count: 16,
      kudos_count: 6,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4149861944',
        summary_polyline:
          'e|puFj{pUBSUV?GDKDEJCZCPKd@dAVHNJLNFPJr@f@hAPv@Rh@NhAP`@VPZJFJH@`@NVNP@JNJb@JHPFH??@?GDL?NCLo@fAWj@i@p@B\\b@\\HJ@PCPM`@Yb@a@hAg@~@g@zAIt@CjAFb@RlAFt@@h@Ef@Uf@CTHVj@b@DL?Tq@|AAb@M|@g@jBO`A]|AOnAMh@CZKTIt@e@`CIx@Mb@MdASx@[~@]|@]n@_@nAYb@Wn@[j@QVIH[t@[j@Y^u@v@Wb@i@r@k@z@_@`@uAdD[jAKhAIXIn@[tE?nAJb@?nAJxADZDhB?jAOb@C^B\\Cf@UjAEn@CHORMd@Wj@GX_@x@OR}@|@s@d@c@ROHUDYNYF]Ps@FMBU@sA`@sATUFaCLe@XQCcAAUEuA?KE]DyA@y@OoAEo@O_@Mm@KaAg@iEiAy@Gi@Am@DaA@c@Fa@Ca@Nm@Ns@^{Af@}AZw@VULg@Po@b@[LgAn@eBj@FEj@Mv@Yt@a@\\W|@a@`@]TIx@Or@Yn@M~@[T@vAo@bBUBE`AOn@?n@DZ?hALdATzA`@r@XhALz@ZbAP`@@r@JT@XI`BCVHPBj@CRF~@BNFXWv@Ax@KTKt@Ot@C`@Il@GdAQn@Wr@K\\On@[^]d@i@Xa@R_@^a@DMF_@J[Va@Fe@Pm@?s@Je@CWHoA@wBB]Eq@?o@Ek@?kAIgAByA\\uEf@cDx@yBVa@nCuDv@_AzAiCVWJYh@gAJOpB_Ff@aBTiAL_APi@B]N{@Do@P{@Ps@VsBXyA\\eC',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4440223872',
      average_speed: 3.476,
      max_speed: 7.6,
      average_cadence: 82.7,
      has_heartrate: true,
      average_heartrate: 165.1,
      max_heartrate: 179.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 588.8,
      elev_low: 578.5,
      pr_count: 8,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Antes de que muriera el reloj',
      distance: 46608.6,
      moving_time: 8544,
      elapsed_time: 12248,
      total_elevation_gain: 411.0,
      type: 'Ride',
      workout_type: 10,
      id: 4145120260,
      external_id:
        '2020-10-03_12-44-25_cc63ec87-956c-49d0-a309-662758806378.tcx',
      upload_id: 4435193421,
      start_date: '2020-10-03T08:19:39Z',
      start_date_local: '2020-10-03T10:19:39Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.39561, -3.696508],
      end_latlng: [40.421938, -3.627845],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.39561,
      start_longitude: -3.696508,
      achievement_count: 30,
      kudos_count: 10,
      comment_count: 0,
      athlete_count: 2,
      photo_count: 0,
      map: {
        id: 'a4145120260',
        summary_polyline:
          'qwpuFd~pUfDdKpEb@z@[b@pAGjBrBpCpDV`DiCtBcDrD_CzEyFdB{DFuAvEgExGoIv@kChCyAj@_C}@QJr@zIfHe@}BbG{@hFkBhBRsBOoOpDyCrBeKxNAd@~@pAaBpB_@LcAsAc@BmE|F_Bx@}D~FcTxPkIbJ{BhF}Hv`@mEjK}HvKcAlC}@hJN~R{A`GeBjCkDlBeOxBuKKyKuCwFIsMtD{F|CeCXwGOeQ{G}@Gu@v@s@Uv@h[f@jGiDlBaEf@_BbBBbJe@`IFfArBdDrFxGgJqM^gKUgImYrTeAXiDfHuJpCoFnD{EzEeFlBsG\\iD`DsJlGqD_J{PrIo_@zIyKb@{E`DiHvOuF|DcNbBeGm@{O^cEv@sAjBiBiBmB|Aw@c@w@uIJsA~@F}@^l@MUaE_EdA}NbNoM|FqJfBmIAqIlCuDkPqEuNuFsCoEwGgGaDmB}C_Ap@u@SsGeJkBHaI}I{Bc@eDbAc@}B{HeEeBOEy@oAcAm@aBPeEvA_AaBu@u@lA[MeCwPIuDyACkDsFmGeGsF_MmG{Hg@{AoAg@mJoK}GuFY_CmCWq@r@mEmDwHuCsGuN_BoB}JcEwA|@o@}@?xAe@FMuBeCqB_CuFy@yDF}BuDmCaEiM{AiBQ}CmAyBa@gCgCwES{B{CoDk@gDaEaL\\w@`P{A~@u@jBmElIoUwTwPa@eAlIgTzAeChI~@zBcBFkBx@[vBgEm@kAcAa@sMVmCqRiAw@kAl@[a@wANmU}w@iGOk@e@Iu@`DqEjCsI|AkBjF}BXaDf@qCzAcDfBkApFeAdA}FnD{CxAqIzCsDpCi@`Ez@pC|BzAzI`Dg@jH_Nh@T~AcC~d@oz@lEcFlFoDfK{C~Aj@`LZlIjCx@YPgBlTnQ~GZFi@o@qAAqDj@iFdEaLb@gDnDeJlB_KnFwIbBXkAmC~@{D`NcTzLkOAZdB{AjL`Ab@gJv@InAwE|]cVpBQj@mB`FsAjAoCdF}FtF}LbAqEfAg@h@oAf@@e@sAVeBdVml@KwBlCaOb@w@jBSTwDf@q@xBvBbA_@pC|DfJwDMgE~BWb@j@BzChCrA~HgEdGiHrHQrHoCfDOnElApL|IlCzCfC~F|@T`@SjEsQlAn@jAwC|MqBXk@W}GjBe@h@{BbDmE~BaBxYbEpGzBzA`BxDbIlQlr@Sp@oDzADh@~D?xAz@|Uh~@wAzBoJtE?bEc@g@}@bAqBVh@xFGlEeF`LkEcCkCt@oBwF}CzB',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4435193421',
      average_speed: 5.455,
      max_speed: 16.0,
      average_watts: 81.9,
      kilojoules: 699.9,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 115.6,
      max_heartrate: 165.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 731.5,
      elev_low: 574.3,
      pr_count: 9,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 3381,
      elapsed_time: 3381,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4135940469,
      external_id:
        '2020-10-01_07-24-22_88af79f4-0969-4b6e-ac69-1b168ba64982.tcx',
      upload_id: 4425430578,
      start_date: '2020-10-01T06:27:01Z',
      start_date_local: '2020-10-01T08:27:01Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 3,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4135940469',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4425430578',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 90.8,
      max_heartrate: 122.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Carrera por la mañana',
      distance: 6258.6,
      moving_time: 1805,
      elapsed_time: 2264,
      total_elevation_gain: 8.3,
      type: 'Run',
      workout_type: null,
      id: 4131449663,
      external_id:
        '2020-09-30_07-00-29_fd7a5c33-8196-4ebe-9828-188455746b38.tcx',
      upload_id: 4420663139,
      start_date: '2020-09-30T06:21:04Z',
      start_date_local: '2020-09-30T08:21:04Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.396617, -3.696127],
      end_latlng: [40.393908, -3.699037],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.396617,
      start_longitude: -3.696127,
      achievement_count: 6,
      kudos_count: 5,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4131449663',
        summary_polyline:
          'y}puFx{pUHV\\j@JHJVBFEHAT^Th@RHHRf@Ln@Zz@l@~@~@b@TDJN^Bn@GN@VFBDTBPXVHHHP`@APGR]h@Qb@i@r@Yn@BLd@b@?`@IXUb@a@`BQ^Ut@]n@Q`@GzAFl@LlBHh@C\\[dBLRf@d@DLGlDSBMJELMjAUv@?PWlACx@Qj@MtAUv@E`@QhAA\\K|@IZE|@U`@Gh@Mh@KPKr@MVGFQd@ANg@`AGVW\\Ol@QVMH[h@QPSl@MLKF}@pA[NYb@uD~EUb@I\\IHM^[jAALDJAHBBCA?XIp@WtAC\\IvEW[?IHyALeER}AJa@[bFM|@@jAE~@BPDSGmAD{CD_ARuBDTAb@IvAS~AGrBBxBJvB@v@Hz@?vBIpAQnAUjAa@~AUb@Qj@k@v@uAvA_Al@i@Vw@Xk@Hq@RmAVm@PcALeAFOCODTKd@K`A[NAl@KfBa@xASb@KrAg@r@a@\\a@\\UPSf@w@Zm@^{@D_@Nq@JcBF[AQB[C{@HkAAoAMoC?eAEW?YFcBCqAB{@LoAToADi@Ps@Xc@Re@Ve@l@m@Zi@hBcCTUTQ\\a@TaAFO^e@HUx@qAN[JOr@{Bj@iAPm@j@wCVeADe@Nk@HaAP}@La@RiAFw@Ha@Le@Vm@BQB]Le@HaAL[^kBL[HcAASOIOU[UCMFURk@Lw@G}@Ko@IaAAYESDe@Jy@X_AL[pA_CV_AAQ_@u@C_@BId@_A`AwAN]',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4420663139',
      average_speed: 3.467,
      max_speed: 9.6,
      average_cadence: 83.4,
      has_heartrate: true,
      average_heartrate: 159.7,
      max_heartrate: 174.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 587.7,
      elev_low: 578.5,
      pr_count: 1,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 3652,
      elapsed_time: 3652,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4126686724,
      external_id:
        '2020-09-29_07-01-11_81d65477-8a51-456c-aa07-66e1f9439979.tcx',
      upload_id: 4415599526,
      start_date: '2020-09-29T05:58:28Z',
      start_date_local: '2020-09-29T07:58:28Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 2,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4126686724',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4415599526',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 110.4,
      max_heartrate: 155.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Empieza la época de llorada de ojos por el frío ',
      distance: 5014.6,
      moving_time: 1496,
      elapsed_time: 1867,
      total_elevation_gain: 15.1,
      type: 'Run',
      workout_type: 0,
      id: 4122492953,
      external_id:
        '2020-09-28_07-04-03_cffd0c59-2675-417f-a12e-05bd1934243c.tcx',
      upload_id: 4411140188,
      start_date: '2020-09-28T06:31:25Z',
      start_date_local: '2020-09-28T08:31:25Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.397057, -3.695715],
      end_latlng: [40.395557, -3.698373],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.397057,
      start_longitude: -3.695715,
      achievement_count: 1,
      kudos_count: 6,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4122492953',
        summary_polyline:
          'q`quFfypUn@v@tAbAp@|@JVBb@HNb@f@XN^r@PJDZ\\^@XTb@TDLCNDN?HCX@PHXHNJh@Hd@NTXT`@S?@PAL[z@W`@o@r@O^APDLJNRNJRATELi@x@Uz@oAnCQx@E`BN`B?TFdA?d@Md@OTATBFZR\\\\DRCJEBUxBWVGPEBELGd@]|@E^Y~AGv@]dBAV{@|DSzAWlAG~@m@xAKd@KP_@pAQVCRGJUVWb@Of@Wj@OPUj@o@x@s@hA]`@Wf@cC`Ds@vAg@nBGl@IXGb@M~AERCbA@^GbA?b@ALFr@D~CFn@BpAAdAIh@A^?VE\\EHETgAlDQXKb@[f@MJEECTFFF?@BROZi@Lg@Te@Pm@Tc@Jk@Pm@F{BEWCwAGo@?}@Gm@?u@Cq@BwCHq@?qAHoA^i@LuAHWV{Af@mAb@w@l@}@v@gA~AqBPa@`AwAn@mALg@|@iBh@sAl@eBH]Rg@^iBPe@Dm@VgBXyAB_@DK@DCIV_CZgA`@iBVu@ZiALk@@UV{AE?KQ[OW[EKD[\\_A@[Ac@]sBE}@@k@Lo@T_@Po@RYPEJ@f@LPJZFB?NMDO?OQWe@[WKIIAEB[Zk@He@Wk@QYE[DM^o@Tg@l@s@Ve@@EAOYc@Wm@KKs@Aa@FKFG@Y@UG[BoAOKK',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4411140188',
      average_speed: 3.352,
      max_speed: 10.1,
      average_cadence: 83.0,
      has_heartrate: true,
      average_heartrate: 156.3,
      max_heartrate: 177.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 587.0,
      elev_low: 578.2,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Vuelta ciclista por la mañana',
      distance: 39155.3,
      moving_time: 6187,
      elapsed_time: 6310,
      total_elevation_gain: 282.6,
      type: 'Ride',
      workout_type: null,
      id: 4118452099,
      external_id:
        '2020-09-27_10-45-26_8ab67491-9cc4-4f72-b758-64d82a34d920.tcx',
      upload_id: 4406839961,
      start_date: '2020-09-27T08:58:44Z',
      start_date_local: '2020-09-27T10:58:44Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.396015, -3.69687],
      end_latlng: [40.396618, -3.696388],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.396015,
      start_longitude: -3.69687,
      achievement_count: 23,
      kudos_count: 8,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4118452099',
        summary_polyline:
          'azpuFl`qUdAa@EYVEzC|LfBVr@O@Qj@XFd@wC|Ep@z@@`@gClEg@bBClAd@~Ea@nBbAz@DVkD|NuBxMmBdG_BnDqIbMuAhDc@bDWjFT|IGnFk@bD}AvD_CtB{BdAiItA}CRcLIaL}CqF?qKxCgHnDoBZ_IWgMgFyCo@aCMWd@Cd@n@`ERxPr@fJIt@_FjBmCVkAvAaZbUiA\\e@fB_C|DeH`BsAl@oFnDeFnFcAvBa@zBu@pUs@vCaAhBu@hDy@lBkBtGKbEs@hFPnKWzGVtMKzBoAzJCdGJpC`@pC\\b@jBn@tBX`AEd@c@xEyH~FeB`FkCrAHrFjBzDTjEnAjDVzLU~Dv@nC]tBu@tB?f@a@bA_Hb@_BjCcEnDcJfAw@r@ZlDvIjCnErA~En@fXg@fFEzAzArR~BdI\\pEE|QXfEdArGTfDK|OAwO[eFaAcGUgGH{Oe@_F{AsE]kBwAaR@qAb@uCVmE[sBGcBd@_K_DmI_DiFuDuIYiAAyVy@uN{Fc]r@q[_A{JReAM_@[@oA`A{FdAl@bEJxKdAhSh@tGhAtGlFnGdB|Ah@~Ar@`OHzLAlHzB|EhBrEvC|Ex@`CXpB^dSRd@HWc@aBI{Bb@sHCeBiCoH_DeFmE}JQw@C}Uy@aOkFoZOiBr@sZw@cKLcB]_Br@mHdAsGGc@USiBBi@]o@iHk@{C}EdBcD`@mB|ByWdS}Al@oBrEmA`B}IdCuFxDgF|E}FlB}FVkChCsDzB}@Nm@h@Kd@uAdA]MoCaISOiPlIwE|@{ChA_B@cCf@iMrDaFGuE|@wBdA_AnAcBxCq@vBgCrF}D|CoAl@wMdByFm@kNRkCVbD]zDFfFYhCFlDh@~LaBtAm@lEuDtBwE|@{CbDwEnDwAbCa@lBKzCN`MoDjFo@jDmApEy@hBqAhLoF\\VdCzHXHvAgANi@h@i@~BmArBu@rCwCr@QdEGvE_BxA{@lEkEnFkD|IgCnC}E|AmBzXwST^KlDHhC[bIN`AnAdCjExEnGmAxABJ_@_@cA@_A`@aF`AsFFoASy@sBCc@c@k@yFcB}K]qVi@uETa@~AFNRUNaAQOYLWrBPfEdA`MzEdHDhD{@pEiCdNiD`FRrH`CxCd@vGDlNoB|D_BxBcCj@kAx@{CRyG[yKb@cGx@gEv@aB|IcMvDsJh@gCbAmHzDcRAUaAeA^qB]}DBuB^wA|BqEA_@c@k@Om@lCeEw@w@G_@sGm@sDuJe@@',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4406839961',
      average_speed: 6.329,
      max_speed: 13.5,
      average_watts: 94.0,
      kilojoules: 581.7,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 119.8,
      max_heartrate: 165.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 678.0,
      elev_low: 578.5,
      pr_count: 5,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Vuelta ciclista por la mañana',
      distance: 24644.2,
      moving_time: 3852,
      elapsed_time: 4063,
      total_elevation_gain: 152.8,
      type: 'Ride',
      workout_type: null,
      id: 4109108834,
      external_id:
        '2020-09-25_07-14-01_203ab7ee-b55e-419e-a272-f798358d0ad3.tcx',
      upload_id: 4396883716,
      start_date: '2020-09-25T06:01:10Z',
      start_date_local: '2020-09-25T08:01:10Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.39572, -3.696727],
      end_latlng: [40.396633, -3.69654],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.39572,
      start_longitude: -3.696727,
      achievement_count: 8,
      kudos_count: 8,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4109108834',
        summary_polyline:
          'expuFp_qU`@RAJDAHNt@pBv@lCRVRJrB@p@ZJZIl@}@rAgArBLl@LLTHFJFT?RuC~EUx@Gb@?zAb@dEA`@[rAJRr@l@DTu@hCaAbEw@lEuAhJe@pBg@fB{BzFy@`BaA|AqDrEeBtCe@fAe@nB_@xDGbCA~ATpGCjFYvBMf@u@nBo@pAq@v@e@^sBhAcB`@gK`BkJBwDi@kFgB}A]sBM}CTs@LiC~@iFtAeFpCeAVoAH{BEgABqBMuAi@gEuBoCcAmE_AwACUZAz@n@fEDbGNbJDdAf@lEA|@QZkC`AqBd@eAAWD}AdBD`@K|BAz@JfB?lA_@`GBz@HZt@z@z@~ApAhAt@lAf@f@Tr@LpBNxMpAtVf@zDl@lDZx@nEtFxBpBVr@Pv@LtCV~CN|FBbKIzEFjA^hAhB`D~AbEnBvCb@z@d@nAd@nBFhADlCZvNJxBItBc@hCAv@bBbS^bBrA|DPrAT|CDvAUlLHhDDhALfAPp@j@xDV~CFvAStNBKNcPYgEkAyGO{BKsCL{F?cFGoBKcBQoAgBsFWqAk@iHg@kIBaA`@gCHmBUsGCcBFsA^}DAk@Ii@u@eBi@mBc@eAg@aAsB_DcBeEaBcDYiAE_AFeDCwMOaE[{DOsCQcByE_XOqAJaJd@eQMqBi@cG@WJaAMOUAw@p@YJwF|@MN^rBH|@LbL`BrYdArHLf@dAxAtDdE`BpA^bAJ~@FrAZfEN`HB|IGzFDp@Px@nBnDpAjDn@hAlBxCh@pAZdAXhBN~GBhELrDDTT@BQUy@Mu@IeCDaBb@_FE{@Wu@c@s@aBaF}CaFsAoDgBmDUkAC}@H_FG{MIcCm@_JS_Bk@gDkDcRMcBB{D^eMLcHGmAs@uGN}AQu@Ci@r@aH|@iFB}@Km@QOWA_APW?WMM]c@uFeAwGa@uDKsDQsNe@iE@e@Ha@LOh@EnDn@zC|@lJbEjAJxACECtCJ`C]xAq@hBmA`CaArD{@nBu@fB[hBCpCTnHzB~B^bCNtD?nBKjBWjI}AnB{@bAs@f@i@l@aAl@yAb@}ATuAFgA@mBE{DQwDAiARgEZgCj@}Bj@sA~GuJx@uAvC_H|@_Dj@uC`AgHdBgIjAyE?EyAuADOZa@L}@E}@YiC?s@Dw@Nw@Xu@fAuBp@eA@Yq@{@K[@MtB}CTi@I?[i@UQ@WECeGYa@O}BeHQWBBC?AHQJDk@EIc@B',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4396883716',
      average_speed: 6.398,
      max_speed: 13.2,
      average_watts: 90.2,
      kilojoules: 347.5,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 121.9,
      max_heartrate: 163.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 678.0,
      elev_low: 578.5,
      pr_count: 3,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Nado nocturno',
      distance: 1925.0,
      moving_time: 1764,
      elapsed_time: 1764,
      total_elevation_gain: 0,
      type: 'Swim',
      id: 4108441475,
      external_id:
        '2020-09-25_00-33-52_30806f4b-8562-4d99-a693-23f9a3253c7d.tcx',
      upload_id: 4396158532,
      start_date: '2020-09-24T20:03:43Z',
      start_date_local: '2020-09-24T22:03:43Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 3,
      comment_count: 3,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4108441475',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4396158532',
      average_speed: 1.091,
      max_speed: 5.0,
      has_heartrate: true,
      average_heartrate: 130.7,
      max_heartrate: 158.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 2253,
      elapsed_time: 2253,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4104848221,
      external_id:
        '2020-09-24_07-34-09_257ec011-e2cd-4b05-b91a-9c3261deb65b.tcx',
      upload_id: 4392369898,
      start_date: '2020-09-24T06:55:33Z',
      start_date_local: '2020-09-24T08:55:33Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 2,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4104848221',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4392369898',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 101.2,
      max_heartrate: 129.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 1278,
      elapsed_time: 1278,
      total_elevation_gain: 0,
      type: 'VirtualRide',
      id: 4104848317,
      external_id:
        '2020-09-24_07-34-12_a923b64b-de99-4a7e-bab2-ec2bec5c7349.tcx',
      upload_id: 4392370031,
      start_date: '2020-09-24T06:26:51Z',
      start_date_local: '2020-09-24T08:26:51Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 1,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4104848317',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4392370031',
      average_speed: 0.0,
      max_speed: 0.0,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 121.6,
      max_heartrate: 161.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Nado nocturno',
      distance: 1625.0,
      moving_time: 1531,
      elapsed_time: 1531,
      total_elevation_gain: 0,
      type: 'Swim',
      id: 4103337574,
      external_id:
        '2020-09-23_20-54-28_32de769d-35df-4fc5-b51f-230755688c6c.tcx',
      upload_id: 4390782682,
      start_date: '2020-09-23T20:17:14Z',
      start_date_local: '2020-09-23T22:17:14Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 3,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4103337574',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4390782682',
      average_speed: 1.061,
      max_speed: 5.0,
      has_heartrate: true,
      average_heartrate: 128.9,
      max_heartrate: 158.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Carrera por la mañana',
      distance: 6009.6,
      moving_time: 1834,
      elapsed_time: 2421,
      total_elevation_gain: 15.0,
      type: 'Run',
      workout_type: null,
      id: 4100242874,
      external_id:
        '2020-09-23_06-56-15_2990c48e-8fa7-44ac-8a54-1c3703e6c82e.tcx',
      upload_id: 4387518010,
      start_date: '2020-09-23T06:14:30Z',
      start_date_local: '2020-09-23T08:14:30Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.395817, -3.697693],
      end_latlng: [40.394317, -3.701587],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.395817,
      start_longitude: -3.697693,
      achievement_count: 4,
      kudos_count: 6,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4100242874',
        summary_polyline:
          'yxpuFreqUX?GSCLLx@?PLd@DFJD\\XNBTQDDRAHBj@ZLDH?f@EPVf@TJBNAFBZTDZAPGNm@n@oAhB@PDJj@f@BD@RWj@]d@e@hAq@hAKFUpACjBd@lCDr@C^Qp@If@BFp@j@JL?RMh@Ro@?c@Vm@Pg@v@yAf@u@\\a@|BcCnAgAhBkBb@YNQNKb@a@h@[RS^Q|AiAr@q@tAcAf@q@f@[xBeBJOf@c@LOb@e@\\g@Vg@ACMb@Yp@IHWHKLMTmApAqDtC]Tm@n@MHc@d@a@VMLg@^cA~@]RGJ_@^a@Vu@\\u@l@GJuAlAwBlCkA`Bs@rAk@rA_@O@ZSz@Ip@?JMZa@jBUp@Kh@E`@o@tDIt@e@hCGp@K\\SnAUd@St@Un@W`Aa@`A]dAOh@Sd@Mn@Qd@]n@QRU`@WZIRqAdBgBjCaApAgA|Ba@xAYdCOzBEzB?vAANN~CV`CERAx@Gr@Mx@Wz@Cj@H[Dg@BmADg@AYDa@UaH?u@I]Bg@GeA?[p@kDDo@PmADs@`@oAp@oAp@cAtAiBl@aAVSrA{BRShAcChAqCT_@P_ARk@\\{A@_@F_@\\oARsABUAQF]b@oBZgBPi@TcAFi@TeABWb@iBN_@^qAMEOOWO[]AG?UTg@H_@B]CkAKm@EmAEUF_AXiAVi@LMXEH?VHVP',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4387518010',
      average_speed: 3.277,
      max_speed: 5.3,
      average_cadence: 83.4,
      has_heartrate: true,
      average_heartrate: 157.6,
      max_heartrate: 176.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 584.3,
      elev_low: 577.2,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Vuelta al agua después de meses ',
      distance: 1700.0,
      moving_time: 1781,
      elapsed_time: 1781,
      total_elevation_gain: 0,
      type: 'Swim',
      id: 4098741900,
      external_id:
        '2020-09-22_20-50-34_791e9bc0-b9dd-4d10-9e3d-1c1e4273c8f5.tcx',
      upload_id: 4385942070,
      start_date: '2020-09-22T20:11:45Z',
      start_date_local: '2020-09-22T22:11:45Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 4,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4098741900',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4385942070',
      average_speed: 0.955,
      max_speed: 7.1,
      has_heartrate: true,
      average_heartrate: 131.0,
      max_heartrate: 183.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 3605,
      elapsed_time: 3605,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4095586106,
      external_id:
        '2020-09-22_08-21-47_94fe56a5-934e-4d52-ac05-47a1e2efd017.tcx',
      upload_id: 4382626281,
      start_date: '2020-09-22T06:20:48Z',
      start_date_local: '2020-09-22T08:20:48Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 3,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4095586106',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4382626281',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 100.0,
      max_heartrate: 135.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Carrera por la mañana',
      distance: 7686.0,
      moving_time: 2295,
      elapsed_time: 2959,
      total_elevation_gain: 21.2,
      type: 'Run',
      workout_type: null,
      id: 4090885344,
      external_id:
        '2020-09-21_07-08-20_3484eb98-d418-486c-aa5b-1947b8f08783.tcx',
      upload_id: 4377678009,
      start_date: '2020-09-21T06:17:29Z',
      start_date_local: '2020-09-21T08:17:29Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.39653, -3.696767],
      end_latlng: [40.39628, -3.696663],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.39653,
      start_longitude: -3.696767,
      achievement_count: 3,
      kudos_count: 9,
      comment_count: 1,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4090885344',
        summary_polyline:
          'i}puFx_qUDHp@d@NPBVf@lAT`AN^f@Zh@PL?NE?BHFVJNLh@P`A@`@EHFJPTPJ@JT@PUx@QXKRY^a@r@M\\FPb@^FHBLEl@e@|@O`@i@n@Wd@Un@SfAEn@@bA^tC@V?XU|@A\\FLf@b@FH?LEd@@Jq@~@G|@GVKLIZQhAEb@Mb@g@tCGf@Mp@C`@S~@KbAAXKn@m@xB?LQh@CREFQp@g@rAsA`DYz@y@rAQRy@pAc@l@k@~@wAfBaAxAKRWdA[|@K\\WjBW`DEhA@|@Lx@Ah@HpCBTFV@\\MpAEn@EXc@pACh@If@Hh@AJGPQ`Au@zAY`@SPQHqAjAkAj@kA^sATMH]Hg@Hy@Tw@LqBPK@GHI@i@Ey@?e@DaBA]E_B?q@Gi@Ao@IKCZWH@BVJCn@CVFn@DLCTAV@HBpBMvCEd@BVGh@?d@Kb@GrAYZCt@MNGfAQr@O|@Yx@c@h@a@lAkATa@HYZy@\\oAJ}@TwABgB@C\\GMiACgAOiBAwBG[?eAPuDPcABq@R{@Jy@Nk@Tm@d@}@f@s@n@s@jBiCr@qAT[JIz@qAx@cBFW@_@Ru@F?DELQb@uALm@N[Li@JSV_ABUJ[b@iCBk@^cCDi@n@mCZgBB]Ro@LWP{@DKVoBH@JKd@mAtAeCpB_CXUl@}@pAgAz@_AlB}APIt@q@TMn@k@VIPQb@W\\Yh@Y^WX[\\k@p@e@dAk@ZUFOVS`@g@ZWLYh@u@j@_ANo@BYESo@}@KIG@sAfAi@x@STKf@SJUV]TcCvAY\\a@Ts@`A[r@SRo@ZSR_@d@_@`@KDQ?WEYKYEk@LYBIAOIa@a@}AqBCWD_@AWBg@USSJYVKSKB?Dk@q@AGEAAG?CFGeAGgAHo@IM@]A]EYIOUY{A]}@Oq@e@_AOu@',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4377678009',
      average_speed: 3.349,
      max_speed: 7.6,
      average_cadence: 83.3,
      has_heartrate: true,
      average_heartrate: 159.7,
      max_heartrate: 173.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 587.4,
      elev_low: 576.0,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Vuelta ciclista a la hora del almuerzo',
      distance: 29998.9,
      moving_time: 5025,
      elapsed_time: 5176,
      total_elevation_gain: 248.9,
      type: 'Ride',
      workout_type: null,
      id: 4086995196,
      external_id:
        '2020-09-20_12-03-57_5f46a9a5-c576-4bf9-aa30-0c3e6cfe6325.tcx',
      upload_id: 4373506356,
      start_date: '2020-09-20T10:36:08Z',
      start_date_local: '2020-09-20T12:36:08Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.395513, -3.6966],
      end_latlng: [40.396547, -3.696488],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.395513,
      start_longitude: -3.6966,
      achievement_count: 12,
      kudos_count: 9,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4086995196',
        summary_polyline:
          '}vpuFv~pU[NBJ|@zAJfAb@hBZr@l@PdDBf@j@G`@cDbFLh@d@p@An@oClFUz@?fAd@vEYvBx@v@?zAm@t@BTK~@wA`GaB~Ke@zBwAlEuCvGyHhKm@lAi@fBq@dGGjCZ|HArGw@pDcA`Cy@~@}AdA_C~@iHnAeDf@sF?yCOqDq@{GqBsBMqCNsK~CaA`@{AfAmBz@wBVmHGsA_@{IyDqD_AeCWWn@Cf@x@jFNvQl@jG?t@Q`@QHiCr@aB\\}AF_BdBDl@InDNhB]zH@~@Pp@tAjC|AxAp@fAf@`@\\zAJ`Lh@nMz@nN|@fGNt@R^`FzFdB|Ad@jAt@pILrJG`NFfB\\dAdBzC|A~DjCbEv@tB^bBJxAR|HAlBXbJEvAa@hDBz@h@jIn@xGVjA|A~EZhDH~DKtKTlF`A`GZ~DEpNGY@oKE_B_@_Ew@yE]wGTeJG}Da@uEwBeI_BuRD{AZmCRqEKPHfCE~Ba@zBAd@^dG~@bKX~AbBtF^vED`FMfIRfF|@lF`@fEGxNMsEB}FUiFiAoHSuDNqOMiC]wCqBuGy@yIa@{GAyAd@oDCuBVcACMGBAPL`BAlCGj@e@`BAd@dBxSxB~HVtCHxEExGD|@Ej@JtDJ|Av@nF`@~FEbKKnCAwAMcADkBEaAN_Gq@sFy@}EUmFJwHNuCIkCs@}FkAsD]_B}AgRFyAb@oBFeACkBTaAY_BEcDJyBZqCAaAKe@}@aBiAkDeDqFuAkDmB}DSw@GqAH_QKeEQoDk@wGqFq[l@_\\}@uJRwA]eB`BqLTyCUa@uAHq@WU}@c@gF_@iCMUsEhBeDNkBxBwI|GgNdKeAZa@pAcCpE{@^wDp@yAd@}GvEcEfEiEbB|DkBzFmF|FuDbA_@`FcAl@Y~BiE|AkBjYkTNLFl@QZIlAHpD]fHJdARd@bBrCnAhA|@pAd@ZxF_AvBCDa@c@sAC]h@yGp@yCPuABwAI[QMiBLWOQs@i@qFs@aDs@qHQmHGcJe@{D?aAhA]|Ez@zBr@fH`DpA`@lHD~@E`A[rEiCvBw@`GeBvB]zD@|Bh@bEtA~Er@hIEZQzLgB|BcA|BuB\\m@f@uAd@sCN_DBsCSaG@qCr@gI~@kChHqJnBsD`CqGf@kBvBsNfBqHv@uDgAuABYb@_BAu@a@aC?gBh@}AjAoBz@mBAYu@u@G]jCoEaAsAmFSkA[MOuAcFa@cAEy@GEQR',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4373506356',
      average_speed: 5.97,
      max_speed: 13.7,
      average_watts: 84.0,
      kilojoules: 422.2,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 120.4,
      max_heartrate: 166.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 678.2,
      elev_low: 578.5,
      pr_count: 1,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 1695,
      elapsed_time: 1695,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4076330461,
      external_id:
        '2020-09-18_07-09-01_40b03457-5c03-4570-9f9b-fd51ddd949f6.tcx',
      upload_id: 4362222222,
      start_date: '2020-09-18T06:39:29Z',
      start_date_local: '2020-09-18T08:39:29Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 2,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4076330461',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4362222222',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 109.2,
      max_heartrate: 147.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 679,
      elapsed_time: 679,
      total_elevation_gain: 0,
      type: 'VirtualRide',
      id: 4076330697,
      external_id:
        '2020-09-18_07-09-06_ccaccea1-54bb-4c8b-86f9-47e42998afcd.tcx',
      upload_id: 4362222461,
      start_date: '2020-09-18T06:27:48Z',
      start_date_local: '2020-09-18T08:27:48Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 1,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4076330697',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4362222461',
      average_speed: 0.0,
      max_speed: 0.0,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 125.3,
      max_heartrate: 153.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 766,
      elapsed_time: 766,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4076330559,
      external_id:
        '2020-09-18_07-09-03_4e039fa1-a77c-4a9d-83d6-3b3a2952a115.tcx',
      upload_id: 4362222341,
      start_date: '2020-09-18T06:14:46Z',
      start_date_local: '2020-09-18T08:14:46Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 1,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4076330559',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4362222341',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 118.0,
      max_heartrate: 139.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Carrera vespertina',
      distance: 8505.5,
      moving_time: 2646,
      elapsed_time: 3468,
      total_elevation_gain: 63.2,
      type: 'Run',
      workout_type: null,
      id: 4069675902,
      external_id:
        '2020-09-16_18-27-57_e3a5b046-b2c1-4aa8-8682-cab2f5c8c814.tcx',
      upload_id: 4355206694,
      start_date: '2020-09-16T17:28:22Z',
      start_date_local: '2020-09-16T19:28:22Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.404822, -3.693442],
      end_latlng: [40.397782, -3.696607],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.404822,
      start_longitude: -3.693442,
      achievement_count: 6,
      kudos_count: 7,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4069675902',
        summary_polyline:
          'cqruF`kpUU?aBJi@Hm@E]Bi@Ia@?YEQ@]Eo@LCCGQEUCEGGYKq@_@a@a@s@cAKUM[KMQg@Mm@Bc@CCwAUs@HYUo@OIKI_@?QI}@Ac@Iq@AkAMgA@OC[@s@IQIGIKBGCKKEESDMVUFa@Cg@Me@E]Ww@YmBYsAIy@Mo@Gk@Mq@AQ@SDG@ECI@ICM?ICSMk@AUCGGi@Oq@K[GKEQE_AMq@Cs@GMWSi@MS@GDk@Ri@L_@RgAZe@R_A\\WDs@Rg@H[LgB\\eDlAg@B]EWFq@TSPSH_BXc@DiBp@U@_AV[F[J[Pa@BkAh@_@CWZQJ{@NWLYFo@X_@FSJk@@_@PEAMW[wAGQ?[U{@I}@Sm@Gc@Cg@O_@S_A?QIm@A]Mc@Ci@@c@Ei@@K\\kAJSTWh@YLMNGNA\\Sp@Wx@c@vAwAh@YXGV@B@FNDBf@A^BNCb@Sn@_@hAQB?Lv@pASn@SjBDz@Cd@On@Gb@OzB_@rA]rCi@h@Cn@IbBYH@d@AvAMFgAu@F_@HqBt@i@Aq@Ta@Fi@NaAH_@LqATc@LcAHc@Hc@A{A\\dAYfAa@v@UfAOd@Kx@]`@EP@x@Qx@I^KdAMb@Od@EzA?]Nw@Ns@TaARa@?YDe@RGJBBdAUPKTYj@UVSRE\\ANJj@DdAUZC^MXC|@Hl@V^\\zAbCJf@BvAIn@a@dBe@p@s@x@s@vAc@bAAFi@De@Lq@b@_@LUBk@PUDeAb@uA^aA`@g@J]PEHIdAAdBIp@DbBEh@D`CDx@ANDT@|AH|A?x@Bl@P?TMJDJJZDT?f@I`@@RBl@@h@ERGFDH^BV@@dCFb@FhAEhAJZEj@?TCNMLGJ@@BQR@b@Z`@HT^rCDt@Av@D`ADz@A\\?d@BFRJz@TD?^SJAb@@XEHFN?NLNRHVN|@P\\LLNJp@bAJJVPb@Hf@h@dAN`@PFM?CA?HEJA~Af@TAzBl@p@Ob@BRHN?bAOb@B`@Ch@Fd@L~@?HFDLB@@VfAJb@EREt@Ez@F~@GVN\\Ev@DLRF^PHLPOhAQz@Cz@UvB@FDHH@HGNAXDh@Nf@Z|A\\N?VE@CZJd@H`@JTEd@R`@@f@F~@Tf@BDMDHL@',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4355206694',
      average_speed: 3.214,
      max_speed: 6.6,
      average_cadence: 80.6,
      has_heartrate: true,
      average_heartrate: 158.0,
      max_heartrate: 177.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 682.9,
      elev_low: 593.2,
      pr_count: 1,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 3320,
      elapsed_time: 3320,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4066970252,
      external_id:
        '2020-09-16_07-24-23_255b387e-f78b-4e70-9208-5f5895fe7bd5.tcx',
      upload_id: 4352353610,
      start_date: '2020-09-16T06:27:49Z',
      start_date_local: '2020-09-16T08:27:49Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 1,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4066970252',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4352353610',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 92.8,
      max_heartrate: 120.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Vuelta ciclista por la mañana',
      distance: 26872.9,
      moving_time: 4380,
      elapsed_time: 4487,
      total_elevation_gain: 166.0,
      type: 'Ride',
      workout_type: null,
      id: 4061823765,
      external_id:
        '2020-09-15_07-12-35_c16d377e-58aa-48e9-b050-b622c55958f6.tcx',
      upload_id: 4346942471,
      start_date: '2020-09-15T05:56:19Z',
      start_date_local: '2020-09-15T07:56:19Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.39491, -3.698308],
      end_latlng: [40.396628, -3.696435],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.39491,
      start_longitude: -3.698308,
      achievement_count: 3,
      kudos_count: 3,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4061823765',
        summary_polyline:
          'espuFliqU?jBFQZKxBId@HTVKb@aC`EANDTp@x@@b@aAnBeAfBYt@In@AzAd@pDCf@[lALVp@j@?Zw@rDo@jB]zAgBxKYfCaAzDuDxImBtCkEzFk@dAq@pBe@|CUxDArB\\hJA~AMrBc@hBm@lBiArBwApAoCbA{GlAsCVe@NuE@iDMmEw@uCgAoA[oBQsBDgC`@eBr@kFtAuFrCs@TkAPaBC{C@cAIgKmE}DeAcBUy@AUXI|@p@lDBlGPpJDdAf@hE?p@MXUR_A\\cD~@aBHcBlBB~@ExCJbCe@jHBfAf@p@pAdC~AvAn@dAh@b@Nd@PfCH|KdAzSb@vEdA|GNh@~E~FnBbBb@lAv@bNDdD@bJExEDbA\\`AzAhClB~EjCdE`ApCZtB`@jSDZJBJOi@_CGoCF_B^oD@u@Gc@K]k@iAm@sBm@}AwCyEgByEyAqCYcAEu@HwDAoM[{GNxBNxG?`JK~DBl@\\tAlBjDdBlEjCdEl@~AXfARzARvMLrDDZH@DS[sAIqABeCd@uFCkA{@mByAmEa@w@kCeEoAkDiBoDSeABmFAmMOqDm@{Iy@_GuAgHyAsIMkAFgHZoRI}BQsBc@qCH_@Ta@@a@IQSEkA~@{Dr@_AFSJ\\xBJrAHjIHzBr@rKh@tKzAvIrF|G`BrA`@z@Hv@BpANdBZjHDnNElED|@b@jAxAhChBrEnCjEv@zB^lBV`PPdGIvBc@|BCt@fBnSZxA~A`F^xE@|EItFB~BTnEX|Bn@nDTtD@zBKfDAvBKrBM_CJoM[cE}@aFImAKoGLwHAkCIeBYyCcBsFY{Aq@{Hg@sHB_Af@oDB{BWcG?mAFwBTeBBsAOu@i@mAwAeEgDuFiA}CkBwDYkAAmAJkEC{My@wM}AuJwC{OKqAh@gVBqDQuCk@eEVqA@][_@Ci@x@kHbAsEHcBOc@UMaBHYCSQOc@_@{F}@oF_@wEa@eTS}ASeCPo@LMfAFdDn@|Br@rJhE|@JpBEzBF|AKj@MfAc@rD}BfG}AvBy@~@QfBIfBDrB^zDpA|DbAlFDpEKhKiBfA[xAu@nAiAz@qA`@eAb@{AVoBJaFWuI@o@ZkFb@iD\\gAh@kAtHgK~@gBpCeHl@wBh@uCbAsHbA_FbAuEd@_BgAiAEO`@mAFu@g@yDAy@Dq@b@{AdByCZ_AGSg@i@Kc@jCaEBQBBK?Ue@]SCYGImA@qDM]KQUe@qAmAaEUe@Gg@e@?',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4346942471',
      average_speed: 6.135,
      max_speed: 11.2,
      average_watts: 80.4,
      kilojoules: 352.0,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 119.2,
      max_heartrate: 160.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 678.0,
      elev_low: 578.5,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 4700,
      elapsed_time: 4700,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4057288111,
      external_id:
        '2020-09-14_07-46-17_026cc1ef-55ae-44ca-825f-29f507fda6cc.tcx',
      upload_id: 4342155606,
      start_date: '2020-09-14T06:26:41Z',
      start_date_local: '2020-09-14T08:26:41Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 4,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4057288111',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4342155606',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 106.7,
      max_heartrate: 151.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Un gps vendría bien ',
      distance: 49827.7,
      moving_time: 8337,
      elapsed_time: 9348,
      total_elevation_gain: 357.2,
      type: 'Ride',
      workout_type: 10,
      id: 4047725386,
      external_id:
        '2020-09-12_11-05-41_294105d6-a636-4e4c-82d5-0ff59ca64a8e.tcx',
      upload_id: 4332020217,
      start_date: '2020-09-12T08:28:26Z',
      start_date_local: '2020-09-12T10:28:26Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.395892, -3.696338],
      end_latlng: [40.39663, -3.696487],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.395892,
      start_longitude: -3.696338,
      achievement_count: 58,
      kudos_count: 11,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4047725386',
        summary_polyline:
          'iypuFb}pUpAt@vAbI`G`B}CtFt@|BgDvHb@vG_@hCfAnAsIdb@cEpJ{HvK{@tBiArLRtLSpF{ArEmB~BcD|A}GrAmKj@cGc@sIiCsEUaOrDmFxC{Cd@sGIuMuFcH}@Ur@n@~DPlTj@hGWbAgEvAyCTeLlKkO|K{@LmDfHyJtCkN~KoFbBoFVsCnCcGxCwB~ByDaJaPnIs`@`JqEGyDp@uErCyHdPuEjD}Bn@mKbAcFo@_P\\eEt@_BnBkBgBoBzAu@m@u@}J\\q@j@Tw@Xh@MWcDVEeBAqB~@sAhBiLjJqM`GaKhBcICoInCkCkNeFuPeGgD{AqCyEgEQo@kCm@kByD_@FYtAk@UkHoJsA^}IsJiB[eDlAkB@_SaLoAaBiFuMqRsVyHiOcQgSqMqMrDg@dBeDk@OAmBeFwDkIcDcHkOoAuA{J_EsAz@s@q@IlAYHMuBkCyByBqFu@sDBiCyCcB_FyNsAyAQyCoAaCa@cCiCyEW{B}CyDqAiGkLq[}AsJyBqQoAcDcEaVnAsGnCHl@iApAEcBUC_AhBSq]`A}JpAsHjEWp@B~AaBpBcQjFwYnUuKtCmChBwHiAiF`@_TfJxEyCzMuEzE[tHtA~C_CzJgCxZeVpPeFhBuBG}A`@s@pImEj`@_CfI`@vCm@f@N`AlBzAl@~Hf@f@a@Ou@aAGeAv@mF[kA]gAmBmJHEpA`BVyAHq@hAaA]kAXiA|GpElVfApCbChRvAhJjKxXlC`KlCrCJjBbArAnB~GjAlBXnDpAxAzEfNzCjB@rDvCzIvChCVbCXQA}Ar@r@~Aq@tJ`EdBlB|D~JlBlC`BbAvBP~G~Ej@{@vBBf@nDfG~EjJlKjCDXnDrExFhGpM`IhIvBxD`BKNvDfCxP^B`@oAlB|@}AnAOvDb@vAbBjAJx@fBHrHbEn@bCzCqAvB^jIlJbBWvHjKpJjErHtIpFtCnFpQpCjMdIuCvI?xLoCvKgFlNuMzAs@hBIHzDo@Tx@]eAHAdBz@xHr@\\vByAhB`BzAsBbEy@tOUrGr@lMqBhGoEvEmLzB}ChCkAjF{@dEN`QuErBKdKmCpO}HtD~InCwCtFeC|CuCfG_@`FmB~FsF`GuDzIgC|E}H~X_TVh@@lHc@tHh@hCzF|GpJ}@Pe@a@kCtBgPc@{@_C@]eAiCkTYaTk@iE\\_BxEl@jOxF|HX|Co@`F{CdMaD`GPxLdDvKC~MiC|BgAhBuBlBsHBkHYaGn@qJbBoF~IkMdE}KzGi^gAwAd@_Cc@uDDyBzCkHo@yBnCiEmAcBuGSaDqJk@H',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4332020217',
      average_speed: 5.977,
      max_speed: 13.9,
      average_watts: 88.4,
      kilojoules: 736.7,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 126.5,
      max_heartrate: 173.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 744.7,
      elev_low: 578.5,
      pr_count: 17,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Cortita - dolor en la patrushca',
      distance: 2142.9,
      moving_time: 685,
      elapsed_time: 1298,
      total_elevation_gain: 6.9,
      type: 'Run',
      workout_type: 0,
      id: 4044879892,
      external_id:
        '2020-09-11_17-38-46_059a60ee-b1ef-4bd0-9d33-9651c8a3cbab.tcx',
      upload_id: 4329020052,
      start_date: '2020-09-11T17:14:35Z',
      start_date_local: '2020-09-11T19:14:35Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.396345, -3.696108],
      end_latlng: [40.388495, -3.698163],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.396345,
      start_longitude: -3.696108,
      achievement_count: 0,
      kudos_count: 5,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4044879892',
        summary_polyline:
          'c|puFt{pUA`@NFNREHAXCLB`@Pj@b@`AFf@T^Tl@Ld@d@V^ALG^CLER@NHNBJ@LC`@Rd@FRFV@B@HJF?DNFJ?HJHCFLPEVY^s@|AIN_@^OT?FJV`@XZ\\l@f@|@bAHFL@@B@PEb@}BnC_@A_@KOCMDIJARHx@C`@ET_@`A_@`@EJ@b@Ah@G\\Oj@C\\DNn@d@FLG~@?p@Sf@WdAGJKd@MV?UBORs@VmANc@r@cBEIIEFQHILa@V]P]RUTc@n@q@d@s@hAoANYfAaA^i@r@q@jAw@b@c@\\U|@w@~AiA^]x@[f@m@d@[d@o@j@c@f@g@t@g@T[~@s@^c@Zk@',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4329020052',
      average_speed: 3.128,
      max_speed: 6.2,
      average_cadence: 80.0,
      has_heartrate: true,
      average_heartrate: 144.7,
      max_heartrate: 164.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 587.7,
      elev_low: 577.2,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Actividad por la mañana',
      distance: 0.0,
      moving_time: 3920,
      elapsed_time: 3920,
      total_elevation_gain: 0,
      type: 'WeightTraining',
      id: 4042758604,
      external_id:
        '2020-09-11_07-45-18_6817d252-e7ad-4e87-a084-8ffdf77af649.tcx',
      upload_id: 4326770360,
      start_date: '2020-09-11T05:59:48Z',
      start_date_local: '2020-09-11T07:59:48Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: null,
      end_latlng: null,
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: null,
      start_longitude: null,
      achievement_count: 0,
      kudos_count: 1,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4042758604',
        summary_polyline: null,
        resource_state: 2
      },
      trainer: true,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4326770360',
      average_speed: 0.0,
      max_speed: 0.0,
      has_heartrate: true,
      average_heartrate: 104.1,
      max_heartrate: 133.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      pr_count: 0,
      total_photo_count: 0,
      has_kudoed: false
    },
    {
      resource_state: 2,
      athlete: {
        id: 28404658,
        resource_state: 1
      },
      name: 'Vuelta ciclista por la mañana',
      distance: 33358.7,
      moving_time: 5090,
      elapsed_time: 5146,
      total_elevation_gain: 290.9,
      type: 'Ride',
      workout_type: null,
      id: 4038223407,
      external_id:
        '2020-09-10_08-12-14_0454ee27-d547-41f0-bd1f-f07d247e7df9.tcx',
      upload_id: 4321970283,
      start_date: '2020-09-10T06:05:17Z',
      start_date_local: '2020-09-10T08:05:17Z',
      timezone: '(GMT+01:00) Europe/Madrid',
      utc_offset: 7200.0,
      start_latlng: [40.395722, -3.696725],
      end_latlng: [40.396612, -3.696412],
      location_city: null,
      location_state: null,
      location_country: null,
      start_latitude: 40.395722,
      start_longitude: -3.696725,
      achievement_count: 56,
      kudos_count: 7,
      comment_count: 0,
      athlete_count: 1,
      photo_count: 0,
      map: {
        id: 'a4038223407',
        summary_polyline:
          'gxpuFp_qUjAWWN?|@rA`Fd@Rr@@f@V`AHf@^LXEj@kCfEHl@f@d@@v@u@~@Sr@_AxAY|@E~Bf@jECd@YdAHXz@v@GpAo@hAsAbFeAdGOIHDC`@w@bGaBxF_CdGqJdNaApCa@~CUlEX~KGnDMrAs@pCaBbDkCjBiBp@iIrAaCRkF@{COwDu@eF_BiESuCb@gJjCoFxC_Cl@kHMgBi@gEwBoDwAqDo@kBKY\\Gv@n@jEXdRl@tHId@s@f@kBj@kEp@kBlBkYtTcAPyBdFk@x@oG~AyAp@oGnEaEdEcAbBk@dBOpA]|OUfDs@pCy@zAs@dD{@nBgB|FCbCKrBq@hENzJUtHVdLg@zFs@`GIdCFnFf@fFf@d@vAh@lCZx@Gb@a@xDuGf@e@fAi@bDq@zD}Bv@QrALnFfBnEZhDbA~DTd@Kj@cCp@{FJgE|DeLd@oBbA{Hp@yHI_DcAkGc@wGFmGKcDTaGw@mHM_GnC_I`@}BNSVI|E\\bAb@bA`AN`AlA`XlArHzEfGbCzBd@lA`@xFV`JFnIG|GHnAxBhE~AbE`DhFp@pB\\jBXnPR`GI`Bc@hCA`A`B|RNz@jBzF^~EIlQZzE`AnFX|DBbBSpMMoGFsH_@mE_AkEMaBCqENiNEgB_@eDyAqE_@gB_B{R?o@f@kDH}A[gKf@yHgAoCwAiEiCeEaBaEiBsDYgAB{F?gIGyGe@}E]sFwEiXOuAh@{[KiCk@mFPiACUe@KaAx@wF`AOPb@dDVrM~AdXbAbHT|@jFvGfB`Bd@dAx@fOFxNGvDF|ATx@jBjDfBfEnCjEv@zBZ`Bj@`YG`Ba@dCAdA|A|RXnAbB`FZpDFrEI`JDjBRnD`A|FX`FOfOIeFF}I]yEgAgGKaC?kDLaFEuGc@kE}A_F[cByAaR@gAb@sCFiAU}Kd@oGA{@aAuBsAcEsDeGoAcD{A}C[oACgBJiQIgDm@oJmAeIeDuQIoAr@}[}@_JLeBSu@Co@z@gHx@sEBaAEYSUqBB[OM[e@cGgAeGa@cE]}Tc@sDBq@Nc@\\InEv@vDjAhFdC`Cv@dHH|B]zD_CbBu@bI}BpB]`CAnBXtGvBhCb@hGJhEQnKsBrCoAnAmArAeCb@{AZeBFkGYyHLcEf@eEf@oBp@aB`HqJlA}BhCyGd@aBxCsPpCeMAWgAcA^wBCcA]yBDgBZqAlCcF?Qq@s@Mi@lCmEoAcBsGYaD_J?YMCYD',
        resource_state: 2
      },
      trainer: false,
      commute: false,
      manual: false,
      private: false,
      visibility: 'everyone',
      flagged: false,
      gear_id: null,
      from_accepted_tag: false,
      upload_id_str: '4321970283',
      average_speed: 6.554,
      max_speed: 13.1,
      average_watts: 100.0,
      kilojoules: 508.9,
      device_watts: false,
      has_heartrate: true,
      average_heartrate: 125.3,
      max_heartrate: 168.0,
      heartrate_opt_out: false,
      display_hide_heartrate_option: true,
      elev_high: 678.0,
      elev_low: 578.5,
      pr_count: 37,
      total_photo_count: 0,
      has_kudoed: false
    }
  ]
};

export default apiEndpoints;
